### ISSUE TITLE
invalid Syntax

### ISSUE THREAD

**Issue by Eumi** [llSourcell/Music_Generator_Demo#10]
I get tis error running on win 10 64bit with python 3.5
python35\python.exe C:\Users\Eumi\Music_Generator_Demo-master\rbm_chords.py
  File "C:\Users\Eumi\Music_Generator_Demo-master\rbm_chords.py", line 30
    print "{} songs processed".format(len(songs))
                                           ^
SyntaxError: invalid syntax

**Comment by fmahmud** [comment]
Try changing it to `print str(len(songs)) + "songs processed."` - this is just an informational print statement, not crucial to the core logic.
Better solution would be to make sure you're using python 2.7

**Comment by Eumi** [comment]
but on windows tensorflow iso nly supported with python 3.5 =O
thanks =)
..for some reasons it gives me old error alltough i changed it ..but i tried it on linux and came much futher ..but it dont process the songs =o ..and also i think i downloaded glob2, on windows,  cause the one it wouldnt download  with python 3 ...so i go on with linux =)
