### ISSUE TITLE
Slicing type error - bug?

### ISSUE THREAD

**Issue by matt60b** [llSourcell/Music_Generator_Demo#13]
Installed all of the dependencies but I get this error:

Traceback (most recent call last):
File "rbm_chords.py", line 116, in <module>
song = song[:np.floor(song.shape[0]/num_timesteps)*num_timsteps]
TypeError: slice indices must be integers or None or have an __index__ method

New to using python/Linux so can't really decipher this myself. Would appreciate some assistance.

**Comment by matt60b** [comment]
To clarify it does the processing and then throws this error

**Comment by Eumi** [comment]
maybe u should try to run it with python 2.7
i got it running on the python version that came with ubuntu 16.04

**Comment by Eumi** [comment]
No wait..open rbm_chords ..and set Batch_size to a number thats smaller than your midi files u have as an input .. like if u have 10 midi files set it to 5 .... or for 18 to 9 ..something like that ..half or so. that when u multiply it the actual number is the result. try that

**Comment by matt60b** [comment]
@Eumi 
Tried this but I still get the error, but when I change batch size to 10 it still says it processed through 122 songs. So I tried removing all but 10 midi files in Pop music and I still get the same error but then it processes 10 songs.

So I don't think its the batch_size or midi folder that has a problem, I'm also working in python 2.7 so I'm really not sure now :/

**Comment by matt60b** [comment]
@Eumi 
OMG, I had the wrong version of numpy...damn dependencies can be a real pain. thank you for replying
